// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.2
// source: ner-apk-proto/user_proto/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserIdGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdGetReq) Reset() {
	*x = UserIdGetReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdGetReq) ProtoMessage() {}

func (x *UserIdGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdGetReq.ProtoReflect.Descriptor instead.
func (*UserIdGetReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserIdGetReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserIdGetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdGetRes) Reset() {
	*x = UserIdGetRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdGetRes) ProtoMessage() {}

func (x *UserIdGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdGetRes.ProtoReflect.Descriptor instead.
func (*UserIdGetRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserIdGetRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       string                 `protobuf:"bytes,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshDeleteReq) Reset() {
	*x = RefreshDeleteReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshDeleteReq) ProtoMessage() {}

func (x *RefreshDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshDeleteReq.ProtoReflect.Descriptor instead.
func (*RefreshDeleteReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshDeleteReq) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type RefreshDeleteRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshDeleteRes) Reset() {
	*x = RefreshDeleteRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshDeleteRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshDeleteRes) ProtoMessage() {}

func (x *RefreshDeleteRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshDeleteRes.ProtoReflect.Descriptor instead.
func (*RefreshDeleteRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshDeleteRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefreshUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       string                 `protobuf:"bytes,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	Newrefresh    string                 `protobuf:"bytes,2,opt,name=newrefresh,proto3" json:"newrefresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshUpdateReq) Reset() {
	*x = RefreshUpdateReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUpdateReq) ProtoMessage() {}

func (x *RefreshUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUpdateReq.ProtoReflect.Descriptor instead.
func (*RefreshUpdateReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshUpdateReq) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

func (x *RefreshUpdateReq) GetNewrefresh() string {
	if x != nil {
		return x.Newrefresh
	}
	return ""
}

type RefreshUpdateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshUpdateRes) Reset() {
	*x = RefreshUpdateRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshUpdateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshUpdateRes) ProtoMessage() {}

func (x *RefreshUpdateRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshUpdateRes.ProtoReflect.Descriptor instead.
func (*RefreshUpdateRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshUpdateRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshUpdateRes) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refresh       string                 `protobuf:"bytes,1,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshGetReq) Reset() {
	*x = RefreshGetReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshGetReq) ProtoMessage() {}

func (x *RefreshGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshGetReq.ProtoReflect.Descriptor instead.
func (*RefreshGetReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshGetReq) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type RefreshGetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshGetRes) Reset() {
	*x = RefreshGetRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshGetRes) ProtoMessage() {}

func (x *RefreshGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshGetRes.ProtoReflect.Descriptor instead.
func (*RefreshGetRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{7}
}

func (x *RefreshGetRes) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshGetRes) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *RefreshGetRes) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetAllUsersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersReq) Reset() {
	*x = GetAllUsersReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersReq) ProtoMessage() {}

func (x *GetAllUsersReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersReq.ProtoReflect.Descriptor instead.
func (*GetAllUsersReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllUsersReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAllUsersReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetAllUsersRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*Users               `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRes) Reset() {
	*x = GetAllUsersRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRes) ProtoMessage() {}

func (x *GetAllUsersRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRes.ProtoReflect.Descriptor instead.
func (*GetAllUsersRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllUsersRes) GetUser() []*Users {
	if x != nil {
		return x.User
	}
	return nil
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{10}
}

func (x *Users) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Users) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Users) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Users) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Users) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type UpdateRoleRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRes) Reset() {
	*x = UpdateRoleRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRes) ProtoMessage() {}

func (x *UpdateRoleRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRes.ProtoReflect.Descriptor instead.
func (*UpdateRoleRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRoleRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleReq) Reset() {
	*x = UpdateRoleReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleReq) ProtoMessage() {}

func (x *UpdateRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleReq.ProtoReflect.Descriptor instead.
func (*UpdateRoleReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRoleReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateRoleReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type StoreRefReshTokenRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRefReshTokenRes) Reset() {
	*x = StoreRefReshTokenRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRefReshTokenRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRefReshTokenRes) ProtoMessage() {}

func (x *StoreRefReshTokenRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRefReshTokenRes.ProtoReflect.Descriptor instead.
func (*StoreRefReshTokenRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{13}
}

func (x *StoreRefReshTokenRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StoreRefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRefreshTokenReq) Reset() {
	*x = StoreRefreshTokenReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRefreshTokenReq) ProtoMessage() {}

func (x *StoreRefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRefreshTokenReq.ProtoReflect.Descriptor instead.
func (*StoreRefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{14}
}

func (x *StoreRefreshTokenReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreRefreshTokenReq) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type ImageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageReq) Reset() {
	*x = ImageReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageReq) ProtoMessage() {}

func (x *ImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageReq.ProtoReflect.Descriptor instead.
func (*ImageReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{15}
}

func (x *ImageReq) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ImageRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageRes) Reset() {
	*x = ImageRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRes) ProtoMessage() {}

func (x *ImageRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRes.ProtoReflect.Descriptor instead.
func (*ImageRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{16}
}

func (x *ImageRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{17}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ConfirmationRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationRegisterReq) Reset() {
	*x = ConfirmationRegisterReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationRegisterReq) ProtoMessage() {}

func (x *ConfirmationRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationRegisterReq.ProtoReflect.Descriptor instead.
func (*ConfirmationRegisterReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{18}
}

func (x *ConfirmationRegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmationRegisterReq) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ConfirmationRegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationRegisterRes) Reset() {
	*x = ConfirmationRegisterRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationRegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationRegisterRes) ProtoMessage() {}

func (x *ConfirmationRegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationRegisterRes.ProtoReflect.Descriptor instead.
func (*ConfirmationRegisterRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{19}
}

func (x *ConfirmationRegisterRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Code          int64                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{20}
}

func (x *RegisterReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterReq) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RegisterRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRes) Reset() {
	*x = RegisterRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRes) ProtoMessage() {}

func (x *RegisterRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRes.ProtoReflect.Descriptor instead.
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{21}
}

func (x *RegisterRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{22}
}

func (x *LoginReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Access        string                 `protobuf:"bytes,1,opt,name=access,proto3" json:"access,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=refresh,proto3" json:"refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRes) Reset() {
	*x = LoginRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRes) ProtoMessage() {}

func (x *LoginRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRes.ProtoReflect.Descriptor instead.
func (*LoginRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{23}
}

func (x *LoginRes) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *LoginRes) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type ConfirmationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationReq) Reset() {
	*x = ConfirmationReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationReq) ProtoMessage() {}

func (x *ConfirmationReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationReq.ProtoReflect.Descriptor instead.
func (*ConfirmationReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{24}
}

func (x *ConfirmationReq) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfirmationReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmationReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ConfirmationRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationRes) Reset() {
	*x = ConfirmationRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationRes) ProtoMessage() {}

func (x *ConfirmationRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationRes.ProtoReflect.Descriptor instead.
func (*ConfirmationRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{25}
}

func (x *ConfirmationRes) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUSerByEmailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUSerByEmailReq) Reset() {
	*x = GetUSerByEmailReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUSerByEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUSerByEmailReq) ProtoMessage() {}

func (x *GetUSerByEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUSerByEmailReq.ProtoReflect.Descriptor instead.
func (*GetUSerByEmailReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{26}
}

func (x *GetUSerByEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{27}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdatePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordReq) Reset() {
	*x = UpdatePasswordReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordReq) ProtoMessage() {}

func (x *UpdatePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordReq.ProtoReflect.Descriptor instead.
func (*UpdatePasswordReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{28}
}

func (x *UpdatePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *UpdatePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *UpdatePasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdatePasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRes) Reset() {
	*x = UpdatePasswordRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRes) ProtoMessage() {}

func (x *UpdatePasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRes.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{29}
}

func (x *UpdatePasswordRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{30}
}

func (x *ResetPasswordReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ResetPasswordReq) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ResetPasswordRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRes) Reset() {
	*x = ResetPasswordRes{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRes) ProtoMessage() {}

func (x *ResetPasswordRes) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRes.ProtoReflect.Descriptor instead.
func (*ResetPasswordRes) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{31}
}

func (x *ResetPasswordRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConfirmationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationResponse) Reset() {
	*x = ConfirmationResponse{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationResponse) ProtoMessage() {}

func (x *ConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{32}
}

func (x *ConfirmationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UpdateUserRespose struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRespose) Reset() {
	*x = UpdateUserRespose{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRespose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRespose) ProtoMessage() {}

func (x *UpdateUserRespose) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRespose.ProtoReflect.Descriptor instead.
func (*UpdateUserRespose) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateUserRespose) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{35}
}

func (x *UserId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteUserr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserr) Reset() {
	*x = DeleteUserr{}
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserr) ProtoMessage() {}

func (x *DeleteUserr) ProtoReflect() protoreflect.Message {
	mi := &file_ner_apk_proto_user_proto_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserr.ProtoReflect.Descriptor instead.
func (*DeleteUserr) Descriptor() ([]byte, []int) {
	return file_ner_apk_proto_user_proto_user_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteUserr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_ner_apk_proto_user_proto_user_proto protoreflect.FileDescriptor

const file_ner_apk_proto_user_proto_user_proto_rawDesc = "" +
	"\n" +
	"#ner-apk-proto/user_proto/user.proto\x12\x04user\"'\n" +
	"\fUserIdGetReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\".\n" +
	"\fUserIdGetRes\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\",\n" +
	"\x10RefreshDeleteReq\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\",\n" +
	"\x10RefreshDeleteRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"L\n" +
	"\x10RefreshUpdateReq\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\x12\x1e\n" +
	"\n" +
	"newrefresh\x18\x02 \x01(\tR\n" +
	"newrefresh\"Q\n" +
	"\x10RefreshUpdateRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\")\n" +
	"\rRefreshGetReq\x12\x18\n" +
	"\arefresh\x18\x01 \x01(\tR\arefresh\"Y\n" +
	"\rRefreshGetRes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\":\n" +
	"\x0eGetAllUsersReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\"1\n" +
	"\x0eGetAllUsersRes\x12\x1f\n" +
	"\x04user\x18\x01 \x03(\v2\v.user.UsersR\x04user\"}\n" +
	"\x05Users\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\")\n" +
	"\rUpdateRoleRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"9\n" +
	"\rUpdateRoleReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"0\n" +
	"\x14StoreRefReshTokenRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"I\n" +
	"\x14StoreRefreshTokenReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\"6\n" +
	"\bImageReq\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"$\n" +
	"\bImageRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xd6\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"C\n" +
	"\x17ConfirmationRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"9\n" +
	"\x17ConfirmationRegisterRes\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"\x8f\x01\n" +
	"\vRegisterReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x03R\x04code\"'\n" +
	"\vRegisterRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\bLoginReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"<\n" +
	"\bLoginRes\x12\x16\n" +
	"\x06access\x18\x01 \x01(\tR\x06access\x12\x18\n" +
	"\arefresh\x18\x02 \x01(\tR\arefresh\"^\n" +
	"\x0fConfirmationReq\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"1\n" +
	"\x0fConfirmationRes\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\")\n" +
	"\x11GetUSerByEmailReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"1\n" +
	"\x0fGetUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"o\n" +
	"\x11UpdatePasswordReq\x12!\n" +
	"\fold_password\x18\x01 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"-\n" +
	"\x11UpdatePasswordRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\x10ResetPasswordReq\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\",\n" +
	"\x10ResetPasswordRes\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x14ConfirmationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"u\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"-\n" +
	"\x11UpdateUserRespose\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x18\n" +
	"\x06UserId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\vDeleteUserr\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xde\a\n" +
	"\vUserService\x120\n" +
	"\bRegister\x12\x11.user.RegisterReq\x1a\x11.user.RegisterRes\x12'\n" +
	"\x05Login\x12\x0e.user.LoginReq\x1a\x0e.user.LoginRes\x12T\n" +
	"\x14ConfirmationRegister\x12\x1d.user.ConfirmationRegisterReq\x1a\x1d.user.ConfirmationRegisterRes\x12@\n" +
	"\x0eGetUSerByEmail\x12\x17.user.GetUSerByEmailReq\x1a\x15.user.GetUserResponse\x12B\n" +
	"\x0eUpdatePassword\x12\x17.user.UpdatePasswordReq\x1a\x17.user.UpdatePasswordRes\x12?\n" +
	"\rResetPassword\x12\x16.user.ResetPasswordReq\x1a\x16.user.ResetPasswordRes\x12I\n" +
	"\x14ConfirmationPassword\x12\x15.user.ConfirmationReq\x1a\x1a.user.ConfirmationResponse\x12-\n" +
	"\n" +
	"DeleteUser\x12\f.user.UserId\x1a\x11.user.DeleteUserr\x126\n" +
	"\n" +
	"UpdateRole\x12\x13.user.UpdateRoleReq\x1a\x13.user.UpdateRoleRes\x12.\n" +
	"\fProfileImage\x12\x0e.user.ImageReq\x1a\x0e.user.ImageRes\x12K\n" +
	"\x11StoreRefreshToken\x12\x1a.user.StoreRefreshTokenReq\x1a\x1a.user.StoreRefReshTokenRes\x126\n" +
	"\n" +
	"RefreshGet\x12\x13.user.RefreshGetReq\x1a\x13.user.RefreshGetRes\x12?\n" +
	"\rRefreshUpdate\x12\x16.user.RefreshUpdateReq\x1a\x16.user.RefreshUpdateRes\x12?\n" +
	"\rRefreshDelete\x12\x16.user.RefreshDeleteReq\x1a\x16.user.RefreshDeleteRes\x129\n" +
	"\vGetallUsers\x12\x14.user.GetAllUsersReq\x1a\x14.user.GetAllUsersRes\x123\n" +
	"\tUserIdGet\x12\x12.user.UserIdGetReq\x1a\x12.user.UserIdGetResB\x0fZ\rgenproto/userb\x06proto3"

var (
	file_ner_apk_proto_user_proto_user_proto_rawDescOnce sync.Once
	file_ner_apk_proto_user_proto_user_proto_rawDescData []byte
)

func file_ner_apk_proto_user_proto_user_proto_rawDescGZIP() []byte {
	file_ner_apk_proto_user_proto_user_proto_rawDescOnce.Do(func() {
		file_ner_apk_proto_user_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ner_apk_proto_user_proto_user_proto_rawDesc), len(file_ner_apk_proto_user_proto_user_proto_rawDesc)))
	})
	return file_ner_apk_proto_user_proto_user_proto_rawDescData
}

var file_ner_apk_proto_user_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_ner_apk_proto_user_proto_user_proto_goTypes = []any{
	(*UserIdGetReq)(nil),            // 0: user.UserIdGetReq
	(*UserIdGetRes)(nil),            // 1: user.UserIdGetRes
	(*RefreshDeleteReq)(nil),        // 2: user.RefreshDeleteReq
	(*RefreshDeleteRes)(nil),        // 3: user.RefreshDeleteRes
	(*RefreshUpdateReq)(nil),        // 4: user.RefreshUpdateReq
	(*RefreshUpdateRes)(nil),        // 5: user.RefreshUpdateRes
	(*RefreshGetReq)(nil),           // 6: user.RefreshGetReq
	(*RefreshGetRes)(nil),           // 7: user.RefreshGetRes
	(*GetAllUsersReq)(nil),          // 8: user.GetAllUsersReq
	(*GetAllUsersRes)(nil),          // 9: user.GetAllUsersRes
	(*Users)(nil),                   // 10: user.Users
	(*UpdateRoleRes)(nil),           // 11: user.UpdateRoleRes
	(*UpdateRoleReq)(nil),           // 12: user.UpdateRoleReq
	(*StoreRefReshTokenRes)(nil),    // 13: user.StoreRefReshTokenRes
	(*StoreRefreshTokenReq)(nil),    // 14: user.StoreRefreshTokenReq
	(*ImageReq)(nil),                // 15: user.ImageReq
	(*ImageRes)(nil),                // 16: user.ImageRes
	(*User)(nil),                    // 17: user.User
	(*ConfirmationRegisterReq)(nil), // 18: user.ConfirmationRegisterReq
	(*ConfirmationRegisterRes)(nil), // 19: user.ConfirmationRegisterRes
	(*RegisterReq)(nil),             // 20: user.RegisterReq
	(*RegisterRes)(nil),             // 21: user.RegisterRes
	(*LoginReq)(nil),                // 22: user.LoginReq
	(*LoginRes)(nil),                // 23: user.LoginRes
	(*ConfirmationReq)(nil),         // 24: user.ConfirmationReq
	(*ConfirmationRes)(nil),         // 25: user.ConfirmationRes
	(*GetUSerByEmailReq)(nil),       // 26: user.GetUSerByEmailReq
	(*GetUserResponse)(nil),         // 27: user.GetUserResponse
	(*UpdatePasswordReq)(nil),       // 28: user.UpdatePasswordReq
	(*UpdatePasswordRes)(nil),       // 29: user.UpdatePasswordRes
	(*ResetPasswordReq)(nil),        // 30: user.ResetPasswordReq
	(*ResetPasswordRes)(nil),        // 31: user.ResetPasswordRes
	(*ConfirmationResponse)(nil),    // 32: user.ConfirmationResponse
	(*UpdateUserRequest)(nil),       // 33: user.UpdateUserRequest
	(*UpdateUserRespose)(nil),       // 34: user.UpdateUserRespose
	(*UserId)(nil),                  // 35: user.UserId
	(*DeleteUserr)(nil),             // 36: user.DeleteUserr
}
var file_ner_apk_proto_user_proto_user_proto_depIdxs = []int32{
	17, // 0: user.UserIdGetRes.user:type_name -> user.User
	10, // 1: user.GetAllUsersRes.user:type_name -> user.Users
	17, // 2: user.ConfirmationRegisterRes.user:type_name -> user.User
	17, // 3: user.ConfirmationRes.user:type_name -> user.User
	17, // 4: user.GetUserResponse.user:type_name -> user.User
	20, // 5: user.UserService.Register:input_type -> user.RegisterReq
	22, // 6: user.UserService.Login:input_type -> user.LoginReq
	18, // 7: user.UserService.ConfirmationRegister:input_type -> user.ConfirmationRegisterReq
	26, // 8: user.UserService.GetUSerByEmail:input_type -> user.GetUSerByEmailReq
	28, // 9: user.UserService.UpdatePassword:input_type -> user.UpdatePasswordReq
	30, // 10: user.UserService.ResetPassword:input_type -> user.ResetPasswordReq
	24, // 11: user.UserService.ConfirmationPassword:input_type -> user.ConfirmationReq
	35, // 12: user.UserService.DeleteUser:input_type -> user.UserId
	12, // 13: user.UserService.UpdateRole:input_type -> user.UpdateRoleReq
	15, // 14: user.UserService.ProfileImage:input_type -> user.ImageReq
	14, // 15: user.UserService.StoreRefreshToken:input_type -> user.StoreRefreshTokenReq
	6,  // 16: user.UserService.RefreshGet:input_type -> user.RefreshGetReq
	4,  // 17: user.UserService.RefreshUpdate:input_type -> user.RefreshUpdateReq
	2,  // 18: user.UserService.RefreshDelete:input_type -> user.RefreshDeleteReq
	8,  // 19: user.UserService.GetallUsers:input_type -> user.GetAllUsersReq
	0,  // 20: user.UserService.UserIdGet:input_type -> user.UserIdGetReq
	21, // 21: user.UserService.Register:output_type -> user.RegisterRes
	23, // 22: user.UserService.Login:output_type -> user.LoginRes
	19, // 23: user.UserService.ConfirmationRegister:output_type -> user.ConfirmationRegisterRes
	27, // 24: user.UserService.GetUSerByEmail:output_type -> user.GetUserResponse
	29, // 25: user.UserService.UpdatePassword:output_type -> user.UpdatePasswordRes
	31, // 26: user.UserService.ResetPassword:output_type -> user.ResetPasswordRes
	32, // 27: user.UserService.ConfirmationPassword:output_type -> user.ConfirmationResponse
	36, // 28: user.UserService.DeleteUser:output_type -> user.DeleteUserr
	11, // 29: user.UserService.UpdateRole:output_type -> user.UpdateRoleRes
	16, // 30: user.UserService.ProfileImage:output_type -> user.ImageRes
	13, // 31: user.UserService.StoreRefreshToken:output_type -> user.StoreRefReshTokenRes
	7,  // 32: user.UserService.RefreshGet:output_type -> user.RefreshGetRes
	5,  // 33: user.UserService.RefreshUpdate:output_type -> user.RefreshUpdateRes
	3,  // 34: user.UserService.RefreshDelete:output_type -> user.RefreshDeleteRes
	9,  // 35: user.UserService.GetallUsers:output_type -> user.GetAllUsersRes
	1,  // 36: user.UserService.UserIdGet:output_type -> user.UserIdGetRes
	21, // [21:37] is the sub-list for method output_type
	5,  // [5:21] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_ner_apk_proto_user_proto_user_proto_init() }
func file_ner_apk_proto_user_proto_user_proto_init() {
	if File_ner_apk_proto_user_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ner_apk_proto_user_proto_user_proto_rawDesc), len(file_ner_apk_proto_user_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ner_apk_proto_user_proto_user_proto_goTypes,
		DependencyIndexes: file_ner_apk_proto_user_proto_user_proto_depIdxs,
		MessageInfos:      file_ner_apk_proto_user_proto_user_proto_msgTypes,
	}.Build()
	File_ner_apk_proto_user_proto_user_proto = out.File
	file_ner_apk_proto_user_proto_user_proto_goTypes = nil
	file_ner_apk_proto_user_proto_user_proto_depIdxs = nil
}
