[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _  # role hierarchy: super > admin > user

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
# r.sub role p.sub bilan mos bo‘lsa, path va method tekshiradi
m = g(r.sub, p.sub) && keyMatch(r.obj, p.obj) && r.act == p.act